package Enumerations;

public enum EspecialidadEnum {

    PASTELERIA,
    CHARCUTERIA,
    COCINA_VEGETARIANA,
    COCINA_MOLECULAR,
    COCINA_FUSION,
    COCINA_AL_VACIO,
    PANADERIA_ARTESANAL,
    COCINA_A_LA_PARRILLA,
    COCINA_DIETETICA,
    COCINA_DE_AUTOR;

}
