package Enumerations;

public enum InteresesCulinariosEnum {

    COMIDA_GOURMET,
    MARIDAJE_DE_VINOS,
    FERMENTACION,
    COCINA_SOSTENIBLE,
    COCINA_INTERNACIONAL,
    PESCADOS_Y_MARISCOS,
    POSTRES_Y_DULCES,
    COCINA_SIN_GLUTEN,
    COMIDA_RAPIDA_ARTESANAL,
    COCINA_A_BASE_DE_PLANTAS;

}